name: Build Executable (Windows)

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get version from version.py
      id: get_version
      run: |
        $VERSION = python -c "from version import __version__; print(__version__)"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build executable with cx_Freeze
      run: python setup.py build

    - name: Zip build output
      run: Compress-Archive -Path build\* -DestinationPath build/windows-build-${{ steps.get_version.outputs.version }}-${{ github.sha }}.zip

    - name: Upload build artifact for workflow
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-${{ steps.get_version.outputs.version }}-${{ github.sha }}
        path: build/windows-build-${{ steps.get_version.outputs.version }}-${{ github.sha }}.zip

    - name: Create GitHub Release
      uses: actions/create-release@v2 # Aktualisierte Version der Action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ steps.get_version.outputs.version }}
        body: |
          Automatischer Build für Version ${{ steps.get_version.outputs.version }} (Commit ${{ github.sha }}).
          (Hier kannst du Release-Notizen hinzufügen)
        draft: false
        prerelease: false
        files: build/windows-build-${{ steps.get_version.outputs.version }}-${{ github.sha }}.zip # Korrekter Input für Artefakte